### PR TITLE
The particles-slider of Enigma-logo is set in a better way & updated TODOs and Issues section in readme

### PR DESCRIPTION
**Pull request by ashuvssut**
The particle-slider is set such as it looks like its in background. The Particle-slider is responsive and fully functional.  All issues related to its functionality are resolved except one issue #9. That one issue was present at the time I forked the project. I could not resolve  that Bug. 

Improved Readability in  Page1.

My changes are updated in Change log in README.md

README.md is improved. TODOs and Issues log added.

### CODE REVIEW

**Comment by ashuvssut** [comment]
> The particle-slider is set such as it looks like its in background. The Particle-slider is responsive and fully functional. All issues related to its functionality are resolved except one issue(see Issue Log in README.md). That one issue was present at the time I forked the project. I could not resolve that Bug.
> 
> Improved Readability in Page1.
> 
> My changes are updated in Change log in README.md
> 
> README.md is improved. TODOs and Issues log added.


** See Changes in Git’s plaintext views. **
https://github.com/EnigmaVSSUT/EnigmaNewWebsite/pull/8.patch\

https://github.com/EnigmaVSSUT/EnigmaNewWebsite/pull/8.diff

**Comment by partha2000** [comment]
@ashuvssut  File a new issue for the problem you are trying to solve. Mention the "issue" in this PR and mention this "PR" there in the issue as well.

**Comment by ashuvssut** [comment]
linked the issue #9

**Comment by ashuvssut** [comment]
you can review directly how it looks by just visiting https://ashuvssut.github.io/EnigmaNewWebsite/ .
If there are some issues then please let me know so that I can fix it and get my PR accepted after that fix

**Comment by partha2000** [comment]
@ashuvssut Didn't get which particle slider you are talking about. Now the logo looks very dull compared to previous versions.

**Comment by ashuvssut** [comment]
> @ashuvssut Didn't get which particle slider you are talking about. Now the logo looks very dull compared to previous versions.

@partha2000 its because I reduced the opacity. And at opacity==1 it didnt looked like a background and it was kinda mixing up with the main content (logo was bright at opacity==1). 

ok i will look for another way to change how it looks.

**Pull request closed without merging**
